# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: noajulkunen
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: iot-temperature-sensor
# "service" is the name of this project. This will also be added to your AWS resource names.
service: backend

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  region: eu-north-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
          Resource:
            - Fn::GetAtt: [Dynamotable, Arn]
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
          Resource:
            - Fn::GetAtt: [LimitTable, Arn]

  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.DYNAMODB_TABLE_NAME}
    EMAIL_ADDRESS: ${self:custom.EMAIL_ADDRESS}
    DYNAMODB_TABLE_NAME_LIMITS: ${self:custom.DYNAMODB_TABLE_NAME_TEMPERATURE}
    RESEND_API_KEY: ${env:RESEND_API_KEY}

custom:
  DYNAMODB_TABLE_NAME: ${env:DYNAMODB_TABLE_NAME}
  EMAIL_ADDRESS: ${env:EMAIL_ADDRESS}
  DYNAMODB_TABLE_NAME_TEMPERATURE: ${env:DYNAMODB_TABLE_NAME_TEMPERATURE}

functions:
  getLimitsBySensor:
    handler: temperature.getLimitsBySensor
    events:
      - httpApi:
          path: /sensor/{sensorId}
          method: get
  createSensorLimits:
    handler: temperature.createSensorLimits
    events:
      - httpApi:
          path: /sensor
          method: post
  updateSensorLimits:
    handler: temperature.updateSensorLimits
    events:
      - httpApi:
          path: /sensor/{sensorId}
          method: put
  getMeasurementById:
    handler: measurement.getMeasurementById
    events:
      - httpApi:
          path: /measurement/{measurementId}
          method: get
  createMeasurement:
    handler: measurement.createMeasurement
    events:
      - httpApi:
          path: /measurement
          method: post
  getAllMeasurements:
    handler: measurement.getAllMeasurements
    events:
      - httpApi:
          path: /measurements
          method: get

resources:
  Resources:
    Dynamotable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.DYNAMODB_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: measurementId
            AttributeType: S
        KeySchema:
          - AttributeName: measurementId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    LimitTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.DYNAMODB_TABLE_NAME_TEMPERATURE}
        AttributeDefinitions:
          - AttributeName: sensorId
            AttributeType: S
        KeySchema:
          - AttributeName: sensorId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
