# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: noajulkunen
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: iot-temperature-sensor
# "service" is the name of this project. This will also be added to your AWS resource names.
service: backend

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  region: eu-north-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
            - dynamodb:Query
          Resource:
            - Fn::GetAtt: [MeasurementsTable, Arn]
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
          Resource:
            - Fn::GetAtt: [TemperatureLimitsTable, Arn]

  environment:
    PRIVATE_KEY: ${env:PRIVATE_KEY}
    DYNAMODB_TABLE_NAME: ${self:custom.DYNAMODB_MEASUREMENTS_TABLE_NAME}
    EMAIL_ADDRESS: ${self:custom.EMAIL_ADDRESS}
    DYNAMODB_TABLE_NAME_LIMITS: ${self:custom.DYNAMODB_TABLE_NAME_TEMPERATURE}
    RESEND_API_KEY: ${env:RESEND_API_KEY}

custom:
  DYNAMODB_MEASUREMENTS_TABLE_NAME: ${env:DYNAMODB_MEASUREMENTS_TABLE_NAME}
  EMAIL_ADDRESS: ${env:EMAIL_ADDRESS}
  DYNAMODB_TABLE_NAME_TEMPERATURE: ${env:DYNAMODB_LIMITS_TABLE_NAME}

functions:
  getLimitsBySensor:
    handler: temperature.getLimitsBySensor
    events:
      - httpApi:
          path: /sensor/{sensorId}
          method: get
  createSensorLimits:
    handler: temperature.createSensorLimits
    events:
      - httpApi:
          path: /sensor
          method: post
  updateSensorLimits:
    handler: temperature.updateSensorLimits
    events:
      - httpApi:
          path: /sensor/{sensorId}
          method: put
  getMeasurementById:
    handler: measurement.getMeasurementById
    events:
      - httpApi:
          path: /measurement/{measurementId}
          method: get
  createMeasurement:
    handler: measurement.createMeasurement
    events:
      - httpApi:
          path: /measurement
          method: post
  getAllMeasurements:
    handler: measurement.getAllMeasurements
    events:
      - httpApi:
          path: /measurements
          method: get

# MeasurementsTable
# sensorId = Partition key, "10:00:3A:BB:AS:1C" - MAC - osoite
# timeStamp = Sort key, 1789718500 - UNIX - aikaleima

# TemperatureLimitsTable
# sensorId = Partition key, "10:00:3A:BB:AS:1C" - MAC - osoite

resources:
  Resources:
    MeasurementsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:DYNAMODB_MEASUREMENTS_TABLE_NAME}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: sensorId
            AttributeType: S
          - AttributeName: timeStamp
            AttributeType: N
        KeySchema:
          - AttributeName: sensorId
            KeyType: HASH
          - AttributeName: timeStamp
            KeyType: RANGE
    TemperatureLimitsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:DYNAMODB_LIMITS_TABLE_NAME}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: sensorId
            AttributeType: S
        KeySchema:
          - AttributeName: sensorId
            KeyType: HASH
